/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiFetchVideoIndexRouteImport } from './routes/api/fetch-video/index'
import { Route as ApiFetchVideoIdRouteImport } from './routes/api/fetch-video/$id'
import { Route as ApiRenderIndexRouteImport } from './routes/api/render/index'
import { Route as ApiRenderIdRouteImport } from './routes/api/render/$id'
import { Route as ApiRenderHealthRouteImport } from './routes/api/render/health'
import { Route as ApiFetchVideoIdFileRouteImport } from './routes/api/fetch-video/$id.file'
import { Route as ApiRenderIdFileRouteImport } from './routes/api/render/$id.file'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFetchVideoIndexRoute = ApiFetchVideoIndexRouteImport.update({
  id: '/api/fetch-video/',
  path: '/api/fetch-video/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFetchVideoIdRoute = ApiFetchVideoIdRouteImport.update({
  id: '/api/fetch-video/$id',
  path: '/api/fetch-video/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRenderIndexRoute = ApiRenderIndexRouteImport.update({
  id: '/api/render/',
  path: '/api/render/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRenderIdRoute = ApiRenderIdRouteImport.update({
  id: '/api/render/$id',
  path: '/api/render/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRenderHealthRoute = ApiRenderHealthRouteImport.update({
  id: '/api/render/health',
  path: '/api/render/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFetchVideoIdFileRoute = ApiFetchVideoIdFileRouteImport.update({
  id: '/file',
  path: '/file',
  getParentRoute: () => ApiFetchVideoIdRoute,
} as any)
const ApiRenderIdFileRoute = ApiRenderIdFileRouteImport.update({
  id: '/file',
  path: '/file',
  getParentRoute: () => ApiRenderIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/fetch-video/$id': typeof ApiFetchVideoIdRouteWithChildren
  '/api/render/$id': typeof ApiRenderIdRouteWithChildren
  '/api/render/health': typeof ApiRenderHealthRoute
  '/api/fetch-video/': typeof ApiFetchVideoIndexRoute
  '/api/render/': typeof ApiRenderIndexRoute
  '/api/fetch-video/$id/file': typeof ApiFetchVideoIdFileRoute
  '/api/render/$id/file': typeof ApiRenderIdFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/fetch-video/$id': typeof ApiFetchVideoIdRouteWithChildren
  '/api/render/$id': typeof ApiRenderIdRouteWithChildren
  '/api/render/health': typeof ApiRenderHealthRoute
  '/api/fetch-video': typeof ApiFetchVideoIndexRoute
  '/api/render': typeof ApiRenderIndexRoute
  '/api/fetch-video/$id/file': typeof ApiFetchVideoIdFileRoute
  '/api/render/$id/file': typeof ApiRenderIdFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/fetch-video/$id': typeof ApiFetchVideoIdRouteWithChildren
  '/api/render/$id': typeof ApiRenderIdRouteWithChildren
  '/api/render/health': typeof ApiRenderHealthRoute
  '/api/fetch-video/': typeof ApiFetchVideoIndexRoute
  '/api/render/': typeof ApiRenderIndexRoute
  '/api/fetch-video/$id/file': typeof ApiFetchVideoIdFileRoute
  '/api/render/$id/file': typeof ApiRenderIdFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/upload'
    | '/api/fetch-video/$id'
    | '/api/render/$id'
    | '/api/render/health'
    | '/api/fetch-video/'
    | '/api/render/'
    | '/api/fetch-video/$id/file'
    | '/api/render/$id/file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/upload'
    | '/api/fetch-video/$id'
    | '/api/render/$id'
    | '/api/render/health'
    | '/api/fetch-video'
    | '/api/render'
    | '/api/fetch-video/$id/file'
    | '/api/render/$id/file'
  id:
    | '__root__'
    | '/'
    | '/api/upload'
    | '/api/fetch-video/$id'
    | '/api/render/$id'
    | '/api/render/health'
    | '/api/fetch-video/'
    | '/api/render/'
    | '/api/fetch-video/$id/file'
    | '/api/render/$id/file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiFetchVideoIdRoute: typeof ApiFetchVideoIdRouteWithChildren
  ApiRenderIdRoute: typeof ApiRenderIdRouteWithChildren
  ApiRenderHealthRoute: typeof ApiRenderHealthRoute
  ApiFetchVideoIndexRoute: typeof ApiFetchVideoIndexRoute
  ApiRenderIndexRoute: typeof ApiRenderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fetch-video/': {
      id: '/api/fetch-video/'
      path: '/api/fetch-video'
      fullPath: '/api/fetch-video/'
      preLoaderRoute: typeof ApiFetchVideoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fetch-video/$id': {
      id: '/api/fetch-video/$id'
      path: '/api/fetch-video/$id'
      fullPath: '/api/fetch-video/$id'
      preLoaderRoute: typeof ApiFetchVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/render/': {
      id: '/api/render/'
      path: '/api/render'
      fullPath: '/api/render/'
      preLoaderRoute: typeof ApiRenderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/render/$id': {
      id: '/api/render/$id'
      path: '/api/render/$id'
      fullPath: '/api/render/$id'
      preLoaderRoute: typeof ApiRenderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/render/health': {
      id: '/api/render/health'
      path: '/api/render/health'
      fullPath: '/api/render/health'
      preLoaderRoute: typeof ApiRenderHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fetch-video/$id/file': {
      id: '/api/fetch-video/$id/file'
      path: '/file'
      fullPath: '/api/fetch-video/$id/file'
      preLoaderRoute: typeof ApiFetchVideoIdFileRouteImport
      parentRoute: typeof ApiFetchVideoIdRoute
    }
    '/api/render/$id/file': {
      id: '/api/render/$id/file'
      path: '/file'
      fullPath: '/api/render/$id/file'
      preLoaderRoute: typeof ApiRenderIdFileRouteImport
      parentRoute: typeof ApiRenderIdRoute
    }
  }
}

interface ApiFetchVideoIdRouteChildren {
  ApiFetchVideoIdFileRoute: typeof ApiFetchVideoIdFileRoute
}

const ApiFetchVideoIdRouteChildren: ApiFetchVideoIdRouteChildren = {
  ApiFetchVideoIdFileRoute: ApiFetchVideoIdFileRoute,
}

const ApiFetchVideoIdRouteWithChildren = ApiFetchVideoIdRoute._addFileChildren(
  ApiFetchVideoIdRouteChildren,
)

interface ApiRenderIdRouteChildren {
  ApiRenderIdFileRoute: typeof ApiRenderIdFileRoute
}

const ApiRenderIdRouteChildren: ApiRenderIdRouteChildren = {
  ApiRenderIdFileRoute: ApiRenderIdFileRoute,
}

const ApiRenderIdRouteWithChildren = ApiRenderIdRoute._addFileChildren(
  ApiRenderIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiFetchVideoIdRoute: ApiFetchVideoIdRouteWithChildren,
  ApiRenderIdRoute: ApiRenderIdRouteWithChildren,
  ApiRenderHealthRoute: ApiRenderHealthRoute,
  ApiFetchVideoIndexRoute: ApiFetchVideoIndexRoute,
  ApiRenderIndexRoute: ApiRenderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
