import type { VideoItem } from "./types";

export const SAMPLE_VIDEOS: VideoItem[] = [
  {
    id: "vid-ember",
    title: "Tro Than — B-roll kịch tính",
    url: "/samples/ember.mp4",
    thumbnail: "/samples/ember.jpg",
    duration: 15,
    source: "sample",
    category: "Hành động",
    resolution: "1280×720",
    aspectRatio: "16:9",
    author: "VEEK Studio",
    views: "Mẫu",
    filmYear: "2024",
    filmGenre: "Hành động",
  },
  {
    id: "vid-steel",
    title: "Thép Xanh — Khoa học viễn tưởng",
    url: "/samples/steel.mp4",
    thumbnail: "/samples/steel.jpg",
    duration: 15,
    source: "sample",
    category: "Khoa học viễn tưởng",
    resolution: "1280×720",
    aspectRatio: "16:9",
    author: "VEEK Studio",
    views: "Mẫu",
    filmYear: "2024",
    filmGenre: "Khoa học viễn tưởng",
  },
  {
    id: "vid-forest",
    title: "Rừng Sương — Giả tưởng trầm",
    url: "/samples/forest.mp4",
    thumbnail: "/samples/forest.jpg",
    duration: 15,
    source: "sample",
    category: "Giả tưởng",
    resolution: "1280×720",
    aspectRatio: "16:9",
    author: "VEEK Studio",
    views: "Mẫu",
    filmYear: "2023",
    filmGenre: "Giả tưởng",
  },
  {
    id: "vid-dusk",
    title: "Hoàng Hôn — Chính kịch",
    url: "/samples/dusk.mp4",
    thumbnail: "/samples/dusk.jpg",
    duration: 20,
    source: "sample",
    category: "Chính kịch",
    resolution: "1280×720",
    aspectRatio: "16:9",
    author: "VEEK Studio",
    views: "Mẫu",
    filmYear: "2022",
    filmGenre: "Chính kịch",
  },
  {
    id: "vid-vertical",
    title: "Shorts dọc — Hook TikTok",
    url: "/samples/vertical.mp4",
    thumbnail: "/samples/vertical.jpg",
    duration: 12,
    source: "sample",
    category: "Shorts",
    resolution: "720×1280",
    aspectRatio: "9:16",
    author: "VEEK Studio",
    views: "Mẫu",
    filmYear: "2025",
    filmGenre: "Hành động",
  },
  {
    id: "vid-signal",
    title: "Tín Hiệu — Test pattern studio",
    url: "/samples/signal.mp4",
    thumbnail: "/samples/signal.jpg",
    duration: 15,
    source: "sample",
    category: "Thử nghiệm",
    resolution: "1280×720",
    aspectRatio: "16:9",
    author: "VEEK Studio",
    views: "Mẫu",
    filmYear: "2026",
    filmGenre: "Thử nghiệm",
  },
];

export const CATEGORIES = [
  "Tất cả",
  "Hành động",
  "Khoa học viễn tưởng",
  "Giả tưởng",
  "Chính kịch",
  "Shorts",
  "Thử nghiệm",
];

export const GENRES = [
  "Chính kịch",
  "Tình cảm",
  "Hành động",
  "Kinh dị",
  "Giả tưởng",
  "Khoa học viễn tưởng",
  "Hoạt hình",
  "Tài liệu",
  "Hài",
  "Tội phạm",
];

export const TONES = [
  "kịch tính, cuốn hút, giàu cảm xúc",
  "trầm lắng, triết lý",
  "hài hước, châm biếm",
  "rùng rợn, căng thẳng",
  "ấm áp, chữa lành",
  "phân tích, sắc sảo",
];
